# @package _global_
app_name: electra-tf2
# specify here default training configuration
defaults:
  - _self_
  - mode: default
  - project: null
  - datamodule: null
  - training: null
  - model: null
  - tokenizer: null
  - logger: null

  # - overide hydra: default
  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
  # custom help
  - override hydra/help: help

# name of the project
project: project_name
dataset: null
work_dir: /workspace/data/tbts/${app_name}
data_dir: ${work_dir}/data
log_dir: ${work_dir}/logs
archive_dir: ${work_dir}/archive
# path to original working directory
runtime_dir: ${hydra:runtime.cwd}

# pretty print config at the start of the run using Rich library
print_config: true
print_resolved_config: false
# disable python warnings if they annoy you
ignore_warnings: True