# @package _global_

# default running mode
default_mode: True


hydra:
  job:
    name: ${project}
  run:
    dir: ${log_dir}/hydra/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${log_dir}/hydra/${hydra.job.name}/multiruns/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}