# @package _global_

defaults:
  - tfrecord_ekon_pretok_512
  - override /training: pretrain_base
  - override /project: ekonelectra_pretok

training:
  phase: 2
  restore_checkpoint: latest
  num_train_steps: 10000
  num_warmup_steps: 1000
  train_batch_size: 32
  learning_rate: 4e-3
  gradient_accumulation_steps: 144

