# @package _global_

defaults:
  - tfrecord_ekon_pretok_256
  - override /project: ekonelectra_pretok
  - override /training: pretrain_electra_base

training:
  phase2: false
  num_train_steps: 10000
  num_warmup_steps: 2000
  train_batch_size: 176
  learning_rate: 6e-3
  gradient_accumulation_steps: 48
  wandb_group: ${training.wandb_project}_p1
