# @package _global_

defaults:
  - tfrecord_ekon_pretok_256
  - override /training: pretrain_base
  - override /project: ekonelectra_pretok

training:
  phase: 1
  num_train_steps: 10000
  num_warmup_steps: 2000
  train_batch_size: 88
  learning_rate: 6e-3
  gradient_accumulation_steps: 48
  wandb_project: ekonelectra_pretok_test
  results_dir: /workspace/data/tbts/eKonPLM/result-test